{% set name = "valmix" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/valmix-{{ version }}.tar.gz
  sha256: 2b7dc93e70ab7287526e9b8853571e92cc7a7315106a4caef34a28bd39e74e1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - textual >=0.57.1

test:
  imports:
    - valmix
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/valmix
  summary: Adjust numerical values from a terminal user interface.
  dev_url: https://github.com/stephane-caron/valmix
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
